#!/bin/bash

set -eo pipefail

help() {
    echo "Usage: $0 [-t title] [-p priority] -m message"
    exit 0
}

exe() { echo "\$ $@" ; "$@" ; }

while getopts t:p:m:v opt; do
    case "${opt}" in 
        t) TITLE=${OPTARG} ;;
        p) PRIORITY=${OPTARG} ;;
        m) MESSAGE=${OPTARG} ;;
        v) VERBOSE="true" ;;
        ?) help ;; # Print usage for invalid param
    esac
done

if [[ -z "$MESSAGE" ]]; then
    echo "Must supply a message (e.g. -m Testing)"
    help
fi

if [[ x"$VERBOSE" = x ]]; then
    curl_opts+=(--silent)
fi
if [[ ! -z "$TITLE" ]]; then 
    curl_opts+=(--form-string "title=${TITLE}")
fi
if [[ ! -z "$PRIORITY" ]]; then 
    curl_opts+=(--form-string "priority=${PRIORITY}") 
fi

if [[ x"$VERBOSE" != x ]]; then
    exe curl "${curl_opts[@]}" \
    --form-string "token=${PUSHOVER_TOKEN}" \
    --form-string "user=${PUSHOVER_USER}" \
    --form-string "message=${MESSAGE}" \
    https://api.pushover.net/1/messages.json
else
    curl -o /dev/null "${curl_opts[@]}" \
    --form-string "token=${PUSHOVER_TOKEN}" \
    --form-string "user=${PUSHOVER_USER}" \
    --form-string "message=${MESSAGE}" \
    https://api.pushover.net/1/messages.json
fi