#!/usr/bin/env bash

set -euo pipefail
DEFAULT=`hostname`
function exe() { echo "\$ $@" ; "$@" ; }

iterm2_set_user_var () {
  printf "\033]1337;SetUserVar=%s=%s\007" "$1" $(printf "%s" "$2" | base64 | tr -d '\n')

  # Change profile
  echo -e "\033]50;SetProfile=SSH\a"

  # Set tab color
  echo -e "\033]6;1;bg;red;brightness;251\a"
  echo -e "\033]6;1;bg;green;brightness;107\a"
  echo -e "\033]6;1;bg;blue;brightness;98\a"

}

# Set the user badge
function set_badge() {
    iterm2_set_user_var badge $1
}

function on_exit() {
  iterm2_set_user_var badge "$DEFAULT"
  echo -e "\033]6;1;bg;*;default\a"
  echo -e "\033]50;SetProfile=Default\a"

}
trap on_exit EXIT

set_badge "$@"

exe /usr/bin/ssh "$@"